### ISSUE TITLE
Release 9.9.9 broke GH action

### ISSUE THREAD

**Issue by anlandu** [jandelgado/gcov2lcov#24]
I assume from the version break that 9.9.9 was not intended to be used publically but rather as a test, but was accidentally marked latest. The new tar filename (with version in the title) breaks the GH action https://github.com/jandelgado/gcov2lcov-action/blob/master/action.yml#L29
Example failuire https://github.com/Azure/AgentBaker/actions/runs/11299411653/job/31430289112?pr=5044#step:7:29

If 9.9.9 is actually intended to be latest release, happy to submit a PR to fix the GH action. Thanks!

**Comment by jandelgado** [comment]
should be fixed now - thanks for the hint
